services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: aaud-backend
    env_file:
      - .env
    restart: always
    ports:
      - "3000:3000"
    networks:
      - aaud-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aaud-frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "8080:80"
    networks:
      - aaud-net

networks:
  aaud-net:
    driver: bridge
