@baseUrl = http://localhost:3000

### LOGIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
 "username": "rvargas",
 "password": "rv.562265"
}



### INCIDENTS
GET {{baseUrl}}/api/incidents



### USERS
GET {{baseUrl}}/api/users



### INVENTORY
GET {{baseUrl}}/api/inventory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6IlTDqWNuaWNvIiwicm9sZUlkIjoyLCJtdXN0Q2hhbmdlUGFzc3dvcmQiOmZhbHNlLCJpYXQiOjE3NzM4NDI1MjYsImV4cCI6MTc3Mzg0NjEyNn0.DoOPpHl12OzcRO-Z_AaVPAbWRwy7cDzos8HkJHdzaPo